---
title: "Code chunks"
author: "Marta"
format: 
  html:
    toc: true
    toc-location: left
    number-sections: true
    grid: 
      sidebar-width: 200px
      body-width: 900px
      margin-width: 400px
      gutter-width: 1.5rem
    theme: 
      light: minty
      dark: superhero
self-contained: true      
lang: it  
bibliography: biblio.bib
reference-location: margin
citation-location: margin
execute:
  echo: false
  
---

@lst-label presents the default settings of the code chunks

```{r}
#| lst-label: lst-default
#| lst-cap: Default settings
head(cars)
```


```{r}
#| echo: false
#| lst-label: lst-echoF
#| lst-cap: Echo FALSE
head(cars)
```



```{r}
#| echo: true
#| eval: false
#| lst-label: lst-echoF
#| lst-cap: Echo TRUE, EVAL FALSE

head(cars)
```


@fig-cap

```{r}
#| label: fig-normal
#| fig-cap: A normal distribution

x = seq(-3,3, length.out = 10000)
dx = dnorm(x)
plot(x, dx, type = "l", cex = 2, lwd = 3)
```


@fig-normalProperties illustrates properties. @fig-normalProperties-1, @fig-normalProperties-2 and @fig-normalProperties-3 

```{r}
#| layout-ncol: 3 
#| label: fig-normalProperties 
#| fig-cap: Normal Distribution 
#| fig-subcap: 
#|  - "Density"
#|  - "Cumulative"
#|  - "Quantile"
  
plot(x, dx, type = "l", cex = 2, lwd = 3)
plot(x, pnorm(x), type = "l", cex = 2, lwd = 3)
plot (pnorm(x), qnorm( pnorm(x)), type = "l", cex = 2, lwd = 3)
```

